"""empty message

Revision ID: b919f65931c0
Revises: 
Create Date: 2025-10-19 20:31:33.520766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b919f65931c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_indices_code'))
        batch_op.drop_index(batch_op.f('ix_market_indices_id'))

    op.drop_table('market_indices')
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_config_id'))
        batch_op.drop_index(batch_op.f('ix_app_config_user_id'))

    op.drop_table('app_config')
    with op.batch_alter_table('stock_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_events_id'))
        batch_op.drop_index(batch_op.f('ix_stock_events_user_stock'))

    op.drop_table('stock_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('smart_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_orders_code'))
        batch_op.drop_index(batch_op.f('ix_smart_orders_id'))
        batch_op.drop_index(batch_op.f('ix_smart_orders_name'))
        batch_op.drop_index(batch_op.f('ix_smart_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_smart_orders_status'))
        batch_op.drop_index(batch_op.f('ix_smart_orders_user_id'))

    op.drop_table('smart_orders')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_id'))
        batch_op.drop_index(batch_op.f('ix_strategies_user_strategy'))

    op.drop_table('strategies')
    with op.batch_alter_table('summary_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summary_account_id'))
        batch_op.drop_index(batch_op.f('ix_summary_account_last_updated'))
        batch_op.drop_index(batch_op.f('ix_summary_account_user_id'))

    op.drop_table('summary_account')
    with op.batch_alter_table('holding_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_stocks_code'))
        batch_op.drop_index(batch_op.f('ix_holding_stocks_id'))
        batch_op.drop_index(batch_op.f('ix_holding_stocks_last_updated'))
        batch_op.drop_index(batch_op.f('ix_holding_stocks_name'))
        batch_op.drop_index(batch_op.f('ix_holding_stocks_userid_code'))
        batch_op.drop_index(batch_op.f('ix_holding_stocks_userid_name'))

    op.drop_table('holding_stocks')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_user_stock'))

    op.drop_table('watchlist')
    with op.batch_alter_table('suggestion_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_code'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_created_at'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_name'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_picked_score'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_user_id'))

    op.drop_table('suggestion_stocks')
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_history_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_history_user_date'))

    op.drop_table('portfolio_history')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_stock_code'))
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))

    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_code', sa.VARCHAR(), nullable=False),
    sa.Column('stock_name', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_date', sa.DATETIME(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('commission', sa.FLOAT(), nullable=True),
    sa.Column('tax', sa.FLOAT(), nullable=True),
    sa.Column('net_amount', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_stock_code'), ['stock_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['transaction_date'], unique=False)

    op.create_table('portfolio_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.DATE(), nullable=False),
    sa.Column('total_assets', sa.FLOAT(), nullable=True),
    sa.Column('total_market_value', sa.FLOAT(), nullable=True),
    sa.Column('cash', sa.FLOAT(), nullable=True),
    sa.Column('daily_pnl', sa.FLOAT(), nullable=True),
    sa.Column('daily_pnl_percent', sa.FLOAT(), nullable=True),
    sa.Column('cumulative_pnl', sa.FLOAT(), nullable=True),
    sa.Column('cumulative_pnl_percent', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_history_user_date'), ['user_id', 'record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_history_id'), ['id'], unique=False)

    op.create_table('suggestion_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('picked_score', sa.FLOAT(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('buy_price', sa.FLOAT(), nullable=True),
    sa.Column('sell_stop_loss_price', sa.FLOAT(), nullable=True),
    sa.Column('sell_take_profit_price', sa.FLOAT(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('buy_smart_order', sa.VARCHAR(), nullable=True),
    sa.Column('sell_smart_order', sa.VARCHAR(), nullable=True),
    sa.Column('buy_smart_order_status', sa.VARCHAR(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('sell_smart_order_status', sa.VARCHAR(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('buy_smart_order_created_at', sa.DATETIME(), nullable=True),
    sa.Column('sell_smart_order_created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestion_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_stocks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_stocks_picked_score'), ['picked_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_stocks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_stocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_stocks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_stocks_code'), ['code'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_code', sa.VARCHAR(), nullable=False),
    sa.Column('stock_name', sa.VARCHAR(), nullable=False),
    sa.Column('added_date', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('target_price', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_user_stock'), ['user_id', 'stock_code'], unique=1)
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_id'), ['id'], unique=False)

    op.create_table('holding_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('current_price', sa.FLOAT(), nullable=True),
    sa.Column('change', sa.FLOAT(), nullable=True),
    sa.Column('change_percent', sa.FLOAT(), nullable=True),
    sa.Column('market_value', sa.FLOAT(), nullable=True),
    sa.Column('holdings', sa.INTEGER(), nullable=True),
    sa.Column('cost_basis_diluted', sa.FLOAT(), nullable=True),
    sa.Column('cost_basis_total', sa.FLOAT(), nullable=True),
    sa.Column('pnl_float', sa.FLOAT(), nullable=True),
    sa.Column('pnl_float_percent', sa.FLOAT(), nullable=True),
    sa.Column('pnl_cumulative', sa.FLOAT(), nullable=True),
    sa.Column('pnl_cumulative_percent', sa.FLOAT(), nullable=True),
    sa.Column('available_shares', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('analysis_report_url', sa.VARCHAR(), nullable=True),
    sa.Column('operation_cmd_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code'),
    sa.UniqueConstraint('user_id', 'name')
    )
    with op.batch_alter_table('holding_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_stocks_userid_name'), ['user_id', 'name'], unique=1)
        batch_op.create_index(batch_op.f('ix_holding_stocks_userid_code'), ['user_id', 'code'], unique=1)
        batch_op.create_index(batch_op.f('ix_holding_stocks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_stocks_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_stocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_stocks_code'), ['code'], unique=False)

    op.create_table('summary_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_market_value', sa.FLOAT(), nullable=True),
    sa.Column('today_pnl', sa.FLOAT(), nullable=True),
    sa.Column('today_pnl_percent', sa.FLOAT(), nullable=True),
    sa.Column('cumulative_pnl', sa.FLOAT(), nullable=True),
    sa.Column('cumulative_pnl_percent', sa.FLOAT(), nullable=True),
    sa.Column('cash', sa.FLOAT(), nullable=True),
    sa.Column('floating_pnl_summary', sa.FLOAT(), nullable=True),
    sa.Column('floating_pnl_summary_percent', sa.FLOAT(), nullable=True),
    sa.Column('total_assets', sa.FLOAT(), nullable=True),
    sa.Column('principal', sa.FLOAT(), nullable=True),
    sa.Column('position_percent', sa.FLOAT(), nullable=True),
    sa.Column('withdrawable', sa.FLOAT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('summary_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summary_account_user_id'), ['user_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_summary_account_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_summary_account_id'), ['id'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_name')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_user_strategy'), ['user_id', 'strategy_name'], unique=1)
        batch_op.create_index(batch_op.f('ix_strategies_id'), ['id'], unique=False)

    op.create_table('smart_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('trigger_condition', sa.VARCHAR(), nullable=False),
    sa.Column('buy_or_sell_price_type', sa.VARCHAR(), nullable=False),
    sa.Column('buy_or_sell_quantity', sa.INTEGER(), nullable=False),
    sa.Column('valid_until', sa.VARCHAR(), nullable=True),
    sa.Column('order_number', sa.VARCHAR(), nullable=True),
    sa.Column('reason_of_ending', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'cancelled'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    with op.batch_alter_table('smart_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smart_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_smart_orders_order_number'), ['order_number'], unique=1)
        batch_op.create_index(batch_op.f('ix_smart_orders_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_smart_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smart_orders_code'), ['code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('profile_picture_url', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    op.create_table('stock_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_code', sa.VARCHAR(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('event_date', sa.DATE(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('ratio', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_events_user_stock'), ['user_id', 'stock_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_events_id'), ['id'], unique=False)

    op.create_table('app_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('theme', sa.VARCHAR(), server_default=sa.text("'light'"), nullable=True),
    sa.Column('notifications_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('market', sa.VARCHAR(), server_default=sa.text("'A-shares'"), nullable=True),
    sa.Column('default_currency', sa.VARCHAR(), server_default=sa.text("'CNY'"), nullable=True),
    sa.Column('language', sa.VARCHAR(), server_default=sa.text("'en'"), nullable=True),
    sa.Column('data_refresh_interval', sa.INTEGER(), server_default=sa.text('(15)'), nullable=True),
    sa.Column('last_synced', sa.DATETIME(), nullable=True),
    sa.Column('open_time_morning_start', sa.TIME(), server_default=sa.text("'09:30:00'"), nullable=True),
    sa.Column('open_time_morning_end', sa.TIME(), server_default=sa.text("'11:30:00'"), nullable=True),
    sa.Column('open_time_afternoon_start', sa.TIME(), server_default=sa.text("'13:00:00'"), nullable=True),
    sa.Column('open_time_afternoon_end', sa.TIME(), server_default=sa.text("'15:00:00'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_config_user_id'), ['user_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_app_config_id'), ['id'], unique=False)

    op.create_table('market_indices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('index_code', sa.VARCHAR(), nullable=False),
    sa.Column('index_name', sa.VARCHAR(), nullable=False),
    sa.Column('current_value', sa.FLOAT(), nullable=True),
    sa.Column('change', sa.FLOAT(), nullable=True),
    sa.Column('change_percent', sa.FLOAT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_indices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_indices_code'), ['index_code'], unique=1)

    # ### end Alembic commands ###
