"""empty message

Revision ID: 6ea57234beed
Revises: 
Create Date: 2025-11-21 17:54:12.604287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6ea57234beed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'market_indices' not in tables:
        op.create_table('market_indices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('index_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('index_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('current_value', sa.Float(), nullable=True),
        sa.Column('change', sa.Float(), nullable=True),
        sa.Column('change_percent', sa.Float(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('market_indices', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_market_indices_index_code'), ['index_code'], unique=True)

    if 'app_config' not in tables:
        op.create_table('app_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
        sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('data_refresh_interval', sa.Integer(), nullable=False),
        sa.Column('last_synced', sa.DateTime(), nullable=True),
        sa.Column('open_time_morning_start', sa.Time(), nullable=False),
        sa.Column('open_time_morning_end', sa.Time(), nullable=False),
        sa.Column('open_time_afternoon_start', sa.Time(), nullable=False),
        sa.Column('open_time_afternoon_end', sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('app_config', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_app_config_user_id'), ['user_id'], unique=True)

    if 'stock_events' not in tables:
        op.create_table('stock_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('event_date', sa.Date(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('ratio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'suggestion_stocks' not in tables:
        op.create_table('suggestion_stocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('picked_score', sa.Float(), nullable=True),
        sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('buy_price', sa.Float(), nullable=True),
        sa.Column('sell_stop_loss_price', sa.Float(), nullable=True),
        sa.Column('sell_take_profit_price', sa.Float(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('buy_smart_order', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('sell_smart_order', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('buy_smart_order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('sell_smart_order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('buy_smart_order_created_at', sa.DateTime(), nullable=True),
        sa.Column('sell_smart_order_created_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('suggestion_stocks', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_suggestion_stocks_code'), ['code'], unique=False)
            batch_op.create_index(batch_op.f('ix_suggestion_stocks_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_suggestion_stocks_name'), ['name'], unique=False)
            batch_op.create_index(batch_op.f('ix_suggestion_stocks_picked_score'), ['picked_score'], unique=False)
            batch_op.create_index(batch_op.f('ix_suggestion_stocks_user_id'), ['user_id'], unique=False)

    if 'watchlist' not in tables:
        op.create_table('watchlist',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('stock_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('added_date', sa.DateTime(), nullable=False),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('target_price', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'stock_code')
        )
        with op.batch_alter_table('watchlist', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('holding_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_stocks_id'))
        batch_op.drop_index(batch_op.f('ix_holding_stocks_userid_code'))
        batch_op.drop_index(batch_op.f('ix_holding_stocks_userid_name'))

    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_history_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_history_user_date'))

    with op.batch_alter_table('smart_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_orders_id'))
        batch_op.drop_index(batch_op.f('ix_smart_orders_last_updated'))

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_id'))
        batch_op.drop_index(batch_op.f('ix_strategies_user_strategy'))

    with op.batch_alter_table('summary_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summary_account_id'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_name'))
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.create_index(batch_op.f('ix_transactions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['transaction_date'], unique=False)

    with op.batch_alter_table('summary_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summary_account_id'), ['id'], unique=False)

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_user_strategy'), ['user_id', 'strategy_name'], unique=1)
        batch_op.create_index(batch_op.f('ix_strategies_id'), ['id'], unique=False)

    with op.batch_alter_table('smart_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_orders_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_smart_orders_id'), ['id'], unique=False)

    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_history_user_date'), ['user_id', 'record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_history_id'), ['id'], unique=False)

    with op.batch_alter_table('holding_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_stocks_userid_name'), ['user_id', 'name'], unique=1)
        batch_op.create_index(batch_op.f('ix_holding_stocks_userid_code'), ['user_id', 'code'], unique=1)
        batch_op.create_index(batch_op.f('ix_holding_stocks_id'), ['id'], unique=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))

    op.drop_table('watchlist')
    with op.batch_alter_table('suggestion_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_user_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_picked_score'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_name'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_created_at'))
        batch_op.drop_index(batch_op.f('ix_suggestion_stocks_code'))

    op.drop_table('suggestion_stocks')
    op.drop_table('stock_events')
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_config_user_id'))

    op.drop_table('app_config')
    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_indices_index_code'))

    op.drop_table('market_indices')
    # ### end Alembic commands ###
