"""empty message

Revision ID: e4f436adfd46
Revises: 6ea57234beed
Create Date: 2025-12-23 13:08:41.741245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e4f436adfd46'
down_revision: Union[str, Sequence[str], None] = '6ea57234beed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'light'"))
        batch_op.alter_column('notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('market',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'A-shares'"))
        batch_op.alter_column('default_currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'CNY'"))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'en'"))
        batch_op.alter_column('data_refresh_interval',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(15)'))
        batch_op.alter_column('open_time_morning_start',
               existing_type=sa.TIME(),
               nullable=False,
               existing_server_default=sa.text("'09:30:00'"))
        batch_op.alter_column('open_time_morning_end',
               existing_type=sa.TIME(),
               nullable=False,
               existing_server_default=sa.text("'11:30:00'"))
        batch_op.alter_column('open_time_afternoon_start',
               existing_type=sa.TIME(),
               nullable=False,
               existing_server_default=sa.text("'13:00:00'"))
        batch_op.alter_column('open_time_afternoon_end',
               existing_type=sa.TIME(),
               nullable=False,
               existing_server_default=sa.text("'15:00:00'"))
        batch_op.drop_index(batch_op.f('ix_app_config_id'))

    with op.batch_alter_table('holding_stocks', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_market_indices_code'))
        batch_op.drop_index(batch_op.f('ix_market_indices_id'))
        batch_op.create_index(batch_op.f('ix_market_indices_index_code'), ['index_code'], unique=True)

    with op.batch_alter_table('smart_orders', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('summary_account', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary_account', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('smart_orders', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('market_indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_indices_index_code'))
        batch_op.create_index(batch_op.f('ix_market_indices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_indices_code'), ['index_code'], unique=1)
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('holding_stocks', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_config_id'), ['id'], unique=False)
        batch_op.alter_column('open_time_afternoon_end',
               existing_type=sa.TIME(),
               nullable=True,
               existing_server_default=sa.text("'15:00:00'"))
        batch_op.alter_column('open_time_afternoon_start',
               existing_type=sa.TIME(),
               nullable=True,
               existing_server_default=sa.text("'13:00:00'"))
        batch_op.alter_column('open_time_morning_end',
               existing_type=sa.TIME(),
               nullable=True,
               existing_server_default=sa.text("'11:30:00'"))
        batch_op.alter_column('open_time_morning_start',
               existing_type=sa.TIME(),
               nullable=True,
               existing_server_default=sa.text("'09:30:00'"))
        batch_op.alter_column('data_refresh_interval',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(15)'))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'en'"))
        batch_op.alter_column('default_currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'CNY'"))
        batch_op.alter_column('market',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'A-shares'"))
        batch_op.alter_column('notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'light'"))

    # ### end Alembic commands ###
